# Generated by Django 5.1.1 on 2024-09-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField(default='')),
                ('FirstName', models.CharField(default='', max_length=50)),
                ('LastName', models.CharField(default='', max_length=50)),
                ('Age', models.IntegerField(default='')),
                ('Department', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
