# Generated by Django 5.1.1 on 2024-10-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0003_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_data',
            name='ProfilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
