# Generated by Django 5.1.1 on 2024-10-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0004_emp_data_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_data',
            name='CTC',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emp_data',
            name='GrossSalary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
