# Generated by Django 5.1.1 on 2024-10-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Panel.emp_data'),
        ),
    ]
